name: news_app
description: "A news app that fetches data from news api"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.5.3
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
